name: ticketview
description: Its a clean Ticket view or Receipt view for Flutter application with some UI customization.
version: 2.0.0
homepage: https://github.com/Sorbh/ticketviewflutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: